#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace delay_light.sv --exe delay_light_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vdelay_light.mk Vdelay_light

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vdelay_light
echo "\nSimulation completed"

